# Generated by Django 5.0.6 on 2024-07-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('task_image', models.ImageField(upload_to='tasks_image/%Y/%m/')),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('W', 'Hard')], max_length=100)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Pre-Beginner', 'Pre-Beginner'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Pre-Expert', 'Pre-Expert'), ('Expert', 'Expert'), ('Master', 'Master'), ('Champion', 'Champion')], max_length=20)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('boots', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(to='coinappAPI.invitedfriends')),
                ('tasks', models.ManyToManyField(to='coinappAPI.tasks')),
                ('user_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinappAPI.telegramdata')),
            ],
        ),
    ]
