# Generated by Django 5.0.6 on 2024-07-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('voin', 'voin'), ('elite', 'elite'), ('master', 'master'), ('grandmaster', 'grandmaster'), ('epic', 'epic'), ('legend', 'legend'), ('mific', 'mific')], max_length=20),
        ),
    ]
