# Generated by Django 5.0.6 on 2024-07-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0002_alter_user_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramData',
            new_name='TelegramDate',
        ),
        migrations.AlterModelOptions(
            name='invitedfriends',
            options={'verbose_name': 'invited_friend', 'verbose_name_plural': 'invited_friends'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['level'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterModelOptions(
            name='telegramdate',
            options={'verbose_name': 'telegram_date', 'verbose_name_plural': 'telegram_dates'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['balance'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='invitedfriends',
            table='invited_friend',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='task',
        ),
        migrations.AlterModelTable(
            name='telegramdate',
            table='telegram_date',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
