# Generated by Django 5.0.6 on 2024-07-04 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0003_rename_telegramdata_telegramdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_updated',
            new_name='last_active',
        ),
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passive',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
