# Generated by Django 5.0.6 on 2024-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0004_rename_last_updated_user_last_active_user_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_per_tap',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
