# Generated by Django 5.0.6 on 2024-07-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0006_alter_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_date',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='shaxzodbek', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('voin', 'voin'), ('elite', 'elite'), ('master', 'master'), ('grandmaster', 'grandmaster'), ('epic', 'epic'), ('legend', 'legend'), ('mythic', 'mythic')], default='voin', max_length=20),
        ),
        migrations.DeleteModel(
            name='TelegramDate',
        ),
    ]
