# Generated by Django 5.0.6 on 2024-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0008_alter_user_add_per_tap_alter_user_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boots',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='coinappAPI.invitedfriends'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='coinappAPI.tasks'),
        ),
    ]
