# Generated by Django 5.0.6 on 2024-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinappAPI', '0009_alter_user_boots_alter_user_friends_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('zero', 'zero'), ('voin', 'voin'), ('elite', 'elite'), ('master', 'master'), ('grandmaster', 'grandmaster'), ('epic', 'epic'), ('legend', 'legend'), ('mythic', 'mythic')], default='zero', max_length=15),
        ),
    ]
