# Generated by Django 5.0.6 on 2024-07-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(default=2)),
                ('energy', models.IntegerField(default=6)),
                ('boots', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('task_image', models.ImageField(upload_to='tasks_image/%Y/%m/')),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('W', 'Hard')], max_length=100)),
                ('bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('level', models.CharField(choices=[('voin', 'voin'), ('elite', 'elite'), ('master', 'master'), ('grandmaster', 'grandmaster'), ('epic', 'epic'), ('legend', 'legend'), ('mythic', 'mythic')], default='voin', max_length=15)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('passive', models.PositiveBigIntegerField(default=0)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('lv_up_amount', models.PositiveBigIntegerField(default=500)),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinAPI.boots')),
                ('friends', models.ManyToManyField(blank=True, to='coinAPI.invitedfriends')),
                ('tasks', models.ManyToManyField(blank=True, to='coinAPI.tasks')),
            ],
        ),
    ]
