# Generated by Django 5.0.6 on 2024-07-13 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinAPI', '0002_alter_user_friends_alter_user_last_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boots',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coinAPI.boots'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='coinAPI.tasks'),
        ),
    ]
