# Generated by Django 5.0.6 on 2024-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinAPI', '0004_alter_user_boots_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boots',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='user',
            name='click',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='coinAPI.tasks'),
        ),
        migrations.DeleteModel(
            name='Boots',
        ),
    ]
