# Generated by Django 5.0.6 on 2024-07-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinAPI', '0005_alter_user_boots_user_click_user_energy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(default=2)),
                ('energy', models.IntegerField(default=6)),
                ('boots', models.IntegerField(default=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='click',
        ),
        migrations.RemoveField(
            model_name='user',
            name='energy',
        ),
        migrations.AlterField(
            model_name='user',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coinAPI.boots'),
        ),
    ]
