# Generated by Django 5.0.6 on 2024-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinAPI', '0007_alter_user_boots_alter_user_friends_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=20),
        ),
    ]
