# Generated by Django 5.0.6 on 2024-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinAPI', '0009_alter_user_boots_alter_user_friends_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boots',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='user',
            name='click',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=6),
        ),
        migrations.DeleteModel(
            name='Boots',
        ),
    ]
