# Generated by Django 5.0.6 on 2024-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinAPI', '0010_alter_user_boots_user_click_user_energy_delete_boots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_img',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
